In [92]:
from scipy.optimize import minimize
import numpy as np
import random, math
import matplotlib.pyplot as plt

#ret = minimize(objective, start, bounds=B, constraints=XC)
#alpha = ret['x']
#This will find the vector ⃗ which minimizes the function objective within the bounds B and the constraints XC.

Objective: 

![test](objective.png)

Start: A vector of zeros. numpy.zeros(N)

Bounds: (0, C) for each element of A

XC:

![Alt text](10.png)

In [93]:
def linearKernel(x, y):
    return np.dot(x, y)

def polynomialKernel(x, y, p=3):
    return (1 + np.dot(x, y)) ** p

def RBFKernel(x, y, sigma=5.0):
    return np.exp(-np.linalg.norm(x-y)**2 / (2 * (sigma ** 2)))

In [94]:
def objective(alpha):
    #Effectively implements the expression that should be minimized (our equation)
    
    for i in range(len(alpha)):
        for j in range(len(alpha)):
            scalarValue += alpha[i] * alpha[j] * P[i][j]

    return scalarValue

In [95]:
#TRAINING DATA
x = np.array([[1, 2], 
              [2, 3], 
              [3, 3], 
              [2, 1], 
              [3, 2]])
t = np.array([1, 1, 1, -1, -1])
print(x[4])
print(t[3])

[3 2]
-1


In [96]:
N = 5
P = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        P[i][j] = t[i]*t[j]*linearKernel(x[i], x[j])

print(P)

[[  5.   8.   9.  -4.  -7.]
 [  8.  13.  15.  -7. -12.]
 [  9.  15.  18.  -9. -15.]
 [ -4.  -7.  -9.   5.   8.]
 [ -7. -12. -15.   8.  13.]]
